language: scala
jdk:
  - openjdk8
scala: 2.12.19
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

install:
  - |
    # update this only when sbt-the-bash-script needs to be updated
    export SBT_LAUNCHER=`grep '^sbt.version=' project/build.properties | cut -d '=' -f 2`
    export SBT_OPTS="-Dfile.encoding=UTF-8"
    curl -L --silent "https://github.com/sbt/sbt/releases/download/v$SBT_LAUNCHER/sbt-$SBT_LAUNCHER.tgz" > $HOME/sbt.tgz
    tar zxf $HOME/sbt.tgz -C $HOME
    sudo rm /usr/local/bin/sbt
    sudo ln -s $HOME/sbt/bin/sbt /usr/local/bin/sbt
script: ./.ci_scripts/validate.sh